# Generated by Django 5.2 on 2025-06-26 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_readiness', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soldier', to=settings.AUTH_USER_MODEL),
        ),
    ]
