# Generated by Django 4.2.24 on 2025-09-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_readiness', '0007_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default-avatar.png', upload_to='profile_images/'),
        ),
    ]
