# Generated by Django 5.2.5 on 2025-11-04 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_readiness', '0008_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('known_allergies', models.TextField(blank=True, help_text='List any known allergies')),
                ('current_medications', models.TextField(blank=True, help_text='Current medications and dosages')),
                ('medical_conditions', models.TextField(blank=True, help_text='Any chronic or significant medical conditions')),
                ('last_medical_checkup', models.DateField(blank=True, null=True)),
                ('next_checkup_due', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('FIT', 'Fit for Duty'), ('LIMITED', 'Limited Duty'), ('UNFIT', 'Unfit for Duty'), ('TEMPORARY', 'Temporary Medical Hold')], default='FIT', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional medical notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soldier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='combat_readiness.soldier')),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
                'ordering': ['-updated_at'],
            },
        ),
    ]
