# Generated by Django 5.2 on 2025-07-08 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.CharField(choices=[('Private', 'Private'), ('Corporal', 'Corporal'), ('Sergeant', 'Sergeant'), ('Lieutenant', 'Lieutenant'), ('Captain', 'Captain'), ('Major', 'Major'), ('Colonel', 'Colonel'), ('General', 'General')], max_length=20)),
                ('unit', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Weapon', 'Weapon'), ('Vehicle', 'Vehicle'), ('Communication', 'Communication'), ('Medical', 'Medical'), ('Other', 'Other')], max_length=20)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Good', 'Good'), ('Needs Repair', 'Needs Repair'), ('Damaged', 'Damaged')], max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='readiness.soldier')),
            ],
        ),
    ]
